# 1. Connecting the Database Link
spring.datasource.url=jdbc:postgresql://localhost:5432/medismaran

# 2. Database Login Credentials
spring.datasource.username=postgres
spring.datasource.password=sharma@8088106422

# 3. Setting the Database Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 4. Enabling Automated Table Management
spring.jpa.hibernate.ddl-auto=update

# 5. Logging SQL Transactions to Terminal
spring.jpa.show-sql=true